openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The YouTube Data API v3 is an API that provides access to YouTube data,
    such as videos, playlists, and channels.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: YouTube Data API v3
  version: v3
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://youtube.googleapis.com/$discovery/rest?version=v3
    version: v1
  x-providerName: googleapis.com
  x-serviceName: youtube
servers:
- url: https://youtube.googleapis.com/
tags:
- name: abuseReports
- name: activities
- name: captions
- name: channelBanners
- name: channels
- name: channelSections
- name: comments
- name: commentThreads
- name: i18nLanguages
- name: i18nRegions
- name: liveBroadcasts
- name: liveChatBans
- name: liveChatMessages
- name: liveChatModerators
- name: liveStreams
- name: members
- name: membershipsLevels
- name: playlistItems
- name: playlists
- name: search
- name: subscriptions
- name: superChatEvents
- name: tests
- name: thirdPartyLinks
- name: thumbnails
- name: videoAbuseReportReasons
- name: videoCategories
- name: videos
- name: watermarks
paths:
  /youtube/v3/commentThreads:
    get:
      description: Retrieves a list of resources, possibly filtered.
      operationId: youtube.commentThreads.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube.force-ssl
        Oauth2c:
        - https://www.googleapis.com/auth/youtube.force-ssl
      tags:
      - commentThreads
      x-dependencies:
      - OnlyOne(allThreadsRelatedToChannelId, channelId, id, videoId);
      - ZeroOrOne(id, maxResults);
      - ZeroOrOne(id, moderationStatus);
      - ZeroOrOne(id, order);
      - ZeroOrOne(id, pageToken);
      - ZeroOrOne(id, searchTerms);
  /youtube/v3/search:
    get:
      description: Retrieves a list of search resources
      operationId: youtube.search.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube
        Oauth2c:
        - https://www.googleapis.com/auth/youtube
      - Oauth2:
        - https://www.googleapis.com/auth/youtube.force-ssl
        Oauth2c:
        - https://www.googleapis.com/auth/youtube.force-ssl
      - Oauth2:
        - https://www.googleapis.com/auth/youtube.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/youtube.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/youtubepartner
        Oauth2c:
        - https://www.googleapis.com/auth/youtubepartner
      tags:
      - search
      x-dependencies:
      - ZeroOrOne(forContentOwner, forDeveloper, forMine, relatedToVideoId);
      - IF forContentOwner==true THEN onBehalfOfContentOwner AND type=='video' AND
        NOT (videoDefinition OR videoDimension OR videoDuration OR videoLicense OR
        videoEmbeddable OR videoSyndicated OR videoType);
      - IF forMine==true THEN type=='video' AND NOT (videoDefinition OR videoDimension
        OR videoDuration OR videoLicense OR videoEmbeddable OR videoSyndicated OR
        videoType);
      - IF relatedToVideoId THEN type=='video' AND NOT (channelId OR channelType OR
        eventType OR location OR locationRadius OR onBehalfOfContentOwner OR order
        OR publishedAfter OR publishedBefore OR q OR topicId OR videoCaption OR videoCategoryId
        OR videoDefinition OR videoDimension OR videoDuration OR videoEmbeddable OR
        videoLicense OR videoSyndicated OR videoType);
      - IF eventType THEN type=='video';
      - AllOrNone(location, locationRadius);
      - IF videoCaption THEN type=='video';
      - IF videoCategoryId THEN type=='video';
      - IF videoDefinition THEN type=='video';
      - IF videoDimension THEN type=='video';
      - IF videoDuration THEN type=='video';
      - IF videoEmbeddable THEN type=='video';
      - IF videoLicense THEN type=='video';
      - IF videoSyndicated THEN type=='video';
      - IF videoType THEN type=='video';
  /youtube/v3/videos:
    get:
      description: Retrieves a list of resources, possibly filtered.
      operationId: youtube.videos.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube
        Oauth2c:
        - https://www.googleapis.com/auth/youtube
      - Oauth2:
        - https://www.googleapis.com/auth/youtube.force-ssl
        Oauth2c:
        - https://www.googleapis.com/auth/youtube.force-ssl
      - Oauth2:
        - https://www.googleapis.com/auth/youtube.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/youtube.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/youtubepartner
        Oauth2c:
        - https://www.googleapis.com/auth/youtubepartner
      tags:
      - videos
      x-dependencies:
      - OnlyOne(chart, id, myRating);
      - ZeroOrOne(maxResults, id);
      - ZeroOrOne(pageToken, id);
      - IF regionCode THEN chart;
      - IF videoCategoryId THEN chart;
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/youtube: Manage your YouTube account
            https://www.googleapis.com/auth/youtube.channel-memberships.creator: See
              a list of your current active channel members, their current level,
              and when they became a member
            https://www.googleapis.com/auth/youtube.force-ssl: See, edit, and permanently
              delete your YouTube videos, ratings, comments and captions
            https://www.googleapis.com/auth/youtube.readonly: View your YouTube account
            https://www.googleapis.com/auth/youtube.upload: Manage your YouTube videos
            https://www.googleapis.com/auth/youtubepartner: View and manage your assets
              and associated content on YouTube
            https://www.googleapis.com/auth/youtubepartner-channel-audit: View private
              information of your YouTube channel relevant during the audit process
              with a YouTube partner
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/youtube: Manage your YouTube account
            https://www.googleapis.com/auth/youtube.channel-memberships.creator: See
              a list of your current active channel members, their current level,
              and when they became a member
            https://www.googleapis.com/auth/youtube.force-ssl: See, edit, and permanently
              delete your YouTube videos, ratings, comments and captions
            https://www.googleapis.com/auth/youtube.readonly: View your YouTube account
            https://www.googleapis.com/auth/youtube.upload: Manage your YouTube videos
            https://www.googleapis.com/auth/youtubepartner: View and manage your assets
              and associated content on YouTube
            https://www.googleapis.com/auth/youtubepartner-channel-audit: View private
              information of your YouTube channel relevant during the audit process
              with a YouTube partner
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
